Cargo.toml, color/Cargo.toml, color/src/lib.rs, color_operations/Cargo.toml, color_operations/src/lib.rs
This brings us up-to-date with https://linebender.org/wiki/canonical-lints/
=> Import the full Linebender lint set

Cargo.lock, color/Cargo.toml, color/src/bitset.rs, color/src/color.rs, color/src/colorspace.rs, color/src/css.rs, color/src/floatfuncs.rs, color/src/gradient.rs, color/src/lib.rs, color/src/parse.rs, color/src/serialize.rs, color/src/tagged.rs, color_operations/Cargo.toml
This is copied from Raph's "koloro" local repository, with lots of fiddly changes to satisfy clippy.
=> Populate first draft of color crate

.github/workflows/ci.yml, color/Cargo.toml, color/src/lib.rs, color/src/tagged.rs, color_operations/Cargo.toml, color_operations/src/lib.rs
* Remove `-Zunstable-options -Zrustdoc-scrape-examples` from CI. It wasn't even enabled for docs.rs and we don't have any examples, so not worth enabling scraping at this point.
* Treat doc warnings as errors. Historically we've not done so due to various `rustdoc` bugs giving false positives but I got it to pass without failure right now, so perhaps better times have arrived.
* Enable the `doc_auto_cfg` feature for docs.rs which will show a little tip next to feature gated functionality informing of the crate feature flag.
=> Match CI doc testing with docs.rs.

color/src/color.rs, color/src/colorspace.rs, color/src/css.rs, color/src/floatfuncs.rs, color/src/gradient.rs, color/src/lib.rs, color/src/parse.rs, color/src/serialize.rs, color/src/tagged.rs
In response to feedback on #3.
One comment that was not addressed was direct conversion between color spaces, as opposed to always going through linear rgb.
=> Cleanups and renames

color/examples/gradient.rs, color/examples/interp.rs, color/examples/parse.rs, color/src/color.rs, color/src/colorspace.rs, color/src/css.rs, color/src/tagged.rs
Add a `convert` method to `ColorSpace`, and migrate logic in the individual color types to use that.
One consequence is that gradient interpolation in Oklch is expected to be faster, as the conversion to Oklab for error evaluation now doesn't go all the way back to linear sRGB.
Also adds examples from koloro crate, which were inadvertently omitted from the initial commit.
Removes `TaggedColor::from_linear_srgb` method, as that functionality can now be expressed more idiomatically with properly typed colors.
=> Move conversion logic into ColorSpace

color/src/colorspace.rs, color/src/css.rs, color/src/tagged.rs
Clipping colors to colorspaces' bounds is useful for e.g. final display or as part of gamut mapping.
A related method would be `Colorspace::is_in_bounds(src: [f32; 3])`, but I'm undecided whether that's useful enough to include. It could have a default implementation (`src == Self::clip(src)`). Roughly the same considerations hold for a const `Colorspace::IS_(UN)BOUNDED`.
=> Add color clipping

color/examples/parse.rs, color/src/color.rs, color/src/colorspace.rs, color/src/css.rs, color/src/lib.rs, color/src/parse.rs, color/src/tagged.rs
Adds the colorspaces and associated logic.
Also fix `map_lightness` implementations, I had forgotten that these don't have the same bounds as Oklab and Oklch.
=> Add Lab and Lch color spaces

color/examples/gradient.rs, color/examples/parse.rs, color/src/colorspace.rs, color/src/dynamic.rs, color/src/gradient.rs, color/src/lib.rs, color/src/missing.rs, color/src/parse.rs, color/src/serialize.rs, color/src/tag.rs
As per discussion, the new name is `DynamicColor`, following the precedent of the `image` crate.
Also do some renames and add some docstrings.
Closes #21. The rename of Bitset closes #17.
=> Merge TaggedColor and CssColor

color/src/lib.rs, color/src/parse.rs
This renames `Error` to `ParseError` and makes it an enumeration rather than a `&static str`.
This doesn't yet improve the data tracked for the error for better reporting.
Fixes #16.
=> Use error enum.

color/examples/parse.rs, color/src/colorspace.rs, color/src/lib.rs, color/src/parse.rs, color/src/serialize.rs, color/src/tag.rs
Add HWB color space, basically following the spec. It's been spot-tested with non-HDR colors.
Serialization is to syntax which can be parsed by CSS Color 4, but doesn't include `%` for W and B, as is done by color.js. It also doesn't strictly follow serialization by the spec, which calls for the color to be lowered to RGB. To me this is an argument in favor of having a separate code path for strict CSS serialization.
In theory, HWB should be able to handle HDR colors with negative values for W and B. In practice, that's a bad idea, and in any case the current code does not roundtrip these correctly. That might be a flaw in the spec, and deserves deeper investigation.
Closes #19
=> Hwb color space

color/src/dynamic.rs
It's now the same as docs for `{Alpha,Opaque}Color::map_lightness`.
=> Copy-paste docs for `DynamicColor::map_lightness`

color/src/color.rs
Also add #[must_use].
(`AlphaColor::difference` was simplified in #7).
=> Simplify `OpaqueColor::difference` as in `AlphaColor:difference`

color/src/colorspace.rs, color/src/lib.rs, color/src/parse.rs, color/src/serialize.rs, color/src/tag.rs
The Linear A98 RGB <-> Linear sRGB matrices are based on the exact rational conversion matrices calculated from the XYZ chromaticities. This crate doesn't need the exact rationals as they're truncated to f32 at compile-time anyway, but it might be worth having to serve as a reference for other people. It would be nice to have agreement across implementations at any given precision.
The same _can_ be done for other basis change matrices, though it becomes somewhat unwieldy as the number of steps combined into the matrix increases; by my calculation element (0,0) of the Linear sRGB to XYZ-D50 matrix with linear Bradford adaptation is exactly `7206783369626736730083375524119595656 / 16526827482518743502029642682152162875`.
This is all based on the assumption that the color spaces' specified …
=> Add Adobe RGB (1998) color space

color/src/colorspace.rs, color/src/lib.rs, color/src/parse.rs, color/src/serialize.rs, color/src/tag.rs
For completeness, as in https://github.com/linebender/color/pull/35 and taking the Bradford matrix in Equation E.1 of https://www.color.org/specification/ICC.1-2022-05.pdf at the given (truncated?) accuracy as normative, the exact matrices would be:
To linear srgb
```
[  19465502010224276276661593551020496311 / 6210803527298350782937583386584271072      -10045266661493418335616520203717568647 / 6210803527298350782937583386584271072       -380925829214284601014311508394428683 / 776350440912293847867197923323033884]
[-337356623761478054942371793176577217279 / 344665082585568555920268859305640519120    660465973240145571160426551266636201223 / 344665082585568555920268859305640519120     2881647679747383054412944838679675439 / 86166270646392138980067214826410129780]
[ …
```
=> Add XYZ-D50 color space

color/src/color.rs, color/src/floatfuncs.rs, color/src/lib.rs, color/src/rgba8.rs, color/src/serialize.rs
Adds Rgba8 type and some conversions and formatting.
This PR also changes the serialization of srgb to use the color function. If legacy RGB serialization is desired, the client can convert to Rgba8 first.
Closes #24.
=> Implementation of Rgba8 type

Cargo.lock, Cargo.toml, color/Cargo.toml, color/README.md, color/src/color.rs, color/src/impl_bytemuck.rs, color/src/lib.rs, color/src/rgba8.rs
`AlphaColor`, `OpaqueColor`, and `PremulColor` are now using `#[repr(transparent)]` and impl the `bytemuck` traits `Pod`, `TransparentWrapper`, and `Zeroable`.
`Rgba8` is now `#[repr(C)]` and impls the `bytemuck` traits `Pod` and `Zeroable`.
The `bytemuck` traits are only available when the new `bytemuck` feature is enabled. It is not enabled by default.
This requires relaxing the forbidding of `unsafe_code` as the impls of the `bytemuck` traits must use `unsafe impl`.
=> Improve interop with `bytemuck` and FFI.

AUTHORS, color/src/colorspace.rs, color/src/lib.rs, color/src/parse.rs, color/src/serialize.rs, color/src/tag.rs
Resolves #20, now implementing all CSS Color Module Level 4 color spaces.
Further:
- Add Tom Churchman to AUTHORS list.
=> Add Rec2020 color space

color/src/lib.rs, color/src/palette/css.rs, color/src/palette/mod.rs
Creates public modules with the constants for colors.
Docstring syntax adapted from bevy_color. I think we should be displaying more actual colors in our doc.
Closes #23
=> Add CSS color constants

color/src/color.rs
This is implemented for both `AlphaColor` and `PremulColor` to return an `OpaqueColor`.
In the case of a `PremulColor`, it will un-premultiply the alpha.
To keep this `const fn`, the `PremulColor::un_premultiply` function had to be marked as `const fn`.
Fixes #46.
=> Add `discard_alpha` utility function.

CHANGELOG.md, color/src/color.rs, color/src/colorspace.rs
These are useful values to have without having to go to the palette. Additionally, this allows for getting the correct value for the colorspace for white without having to go through a conversion.
Fixes #63.
=> Add `BLACK`, `WHITE`, `TRANSPARENT` constants to color types.

CHANGELOG.md, color/src/color.rs
This better fits with the naming scheme in other Linebender crates.
Fixes #62.
=> Rename `mul_alpha` to `multiply_alpha`

CHANGELOG.md, Cargo.lock, color/Cargo.toml, color/README.md, color/src/color.rs, color/src/lib.rs, color/src/rgba8.rs
This adds support for `serde::Deserialize` and `serde::Serialize` using `serde-derive` for `AlphaColor`, `OpaqueColor`, `PremulColor`, `Rgba8`.
This does not provide it for `DynamicColor` to avoid dealing with the non-exhaustive `ColorSpaceTag`.
It uses `derive` rather than hand-implementing the traits as the latter is very verbose and most things using `serde` will already have enabled the `derive` feature. (This is also true for the other Linebender crates.)
=> Optionally support `serde`.

AUTHORS, CHANGELOG.md, color/README.md, color/src/color.rs, color/src/impl_bytemuck.rs, color/src/lib.rs, color/src/rgba8.rs
Packing a `PremulColor` to 8 bit channels is a common operation and is done in Vello, so we now have support for a `PremulRgb8a` and some `to_u32` operations as well.
=> Add `PremulRgba8`, `Rgba8::to_u32`

CHANGELOG.md, color/src/color.rs
This is similar to `OpaqueColor::with_alpha`, but allows modifying the alpha channel on an `AlphaColor`.
This can be done via `map`, but this is `const`, so it can result in better code in scenarios like:
```
let c = color::palette::css::GOLDENROD.with_alpha(0.5);
```
=> Add `AlphaColor::with_alpha`

CHANGELOG.md, color/src/dynamic.rs, color/src/missing.rs, color/src/tag.rs
Using `DynamicColor` for color stops in Peniko will require this (when Peniko's `serde` feature is enabled).
=> Impl `serde` for `DynamicColor`

color/src/rgba8.rs
Also, add a short sanity check test.
Based on feedback from @DJMcNab in PR #66.
=> Use `from_be_bytes` for `Rgba8::to_u32`

CHANGELOG.md, color/src/dynamic.rs, color/src/missing.rs
If the alpha channel is missing, these operations will do nothing.
Additionally, mark some functions on `Missing` as `const`.
=> Add `with_alpha` and `multiply_alpha` on `DynamicColor`

CHANGELOG.md, color/src/dynamic.rs, color/src/missing.rs, color/src/tag.rs
Also, impl `Hash` on `ColorSpaceTag`, `Missing` in support.
This is useful for using `DynamicColor` within a cache key or for memoizing, but does not match the behavior of Rust float types.
=> Implement `Hash`, `PartialEq` for `DynamicColor`

CHANGELOG.md, color/src/rgba8.rs
This matches the WebGPU spec which states that the internal layout of values is such that values in host-shared buffers are stored in little-endian format: https://www.w3.org/TR/WGSL/#internal-value-layout
=> `(Premul)Rgba8::to_u32` now returns in little endian format.

color/src/color.rs
This links to the examples, and prevents having to duplicate/keep-in-sync the documentation.
=> Refer some AlphaColor method docs to OpaqueColor

CHANGELOG.md, color/src/color.rs
This is needed in Peniko when a `Gradient` has a `HueDirection` member.
=> `HueDirection` now impls `PartialEq`

CHANGELOG.md, color/src/color.rs
This is needed for adding `HueDirection` to `Gradient` in Peniko.
=> Add `serde` for `HueDirection`

CHANGELOG.md, color/README.md, color/src/color.rs, color/src/impl_bytemuck.rs, color/src/lib.rs, color/src/tag.rs
These now impl `CheckedBitPattern`, `Contiguous`, `NoUninit`, and `Zeroable`. They do not impl `Pod` as they are only valid for a subset of the bit patterns.
Additionally, these types are now `repr(u8)` and have directly assigned integer values so that we can be sure that the impl of the `Contiguous` trait is correct.
This will likely be useful when working with gradients in Vello and it has to encode things to the draw stream.
It may also be useful when we're doing a C FFI in the future.
=> Add `bytemuck` support for `HueDirection`, and `ColorSpaceTag`

CHANGELOG.md, color/src/color.rs
There's no need for each `ColorSpace` to have to impl `PartialEq` since they're zero-sized types.
=> Derive PartialEq by hand to avoid ColorSpace: PartialEq bound

color/src/color.rs
This is a backport of a change from Raph made in the CPU sparse strips experiment.
When converting from `f32` to `u8`, the code was clamping to be sure that the values were within range. This was necessary in the past, but hasn't been needed for some years now, since <https://github.com/rust-lang/rust/issues/10184>. This clamping is not necessary and the compiler is not optimizing it away as of Rust 1.83 on Apple Silicon.
=> Rely on defined saturation behavior for f32 to u8 casts

CHANGELOG.md, color/src/cache_key.rs, color/src/color.rs, color/src/dynamic.rs, color/src/impl_bytemuck.rs, color/src/lib.rs
This will be useful for Vello.
This is done through two new traits, `BitEq` and `BitHash`. These are used in the `Eq` and `Hash` implementations of `CacheKey<T>`.
These traits are implemented for f32, and the colour types in this crate (except the 8 bit types)
=> `CacheKey` type for maps which use colours as keys

.typos.toml
We should be consistent in our spelling.
=> Treat "colour" as a typo for "color"

color/README.md, color/src/lib.rs
Moves the "Main types" section above the "Scope and goals" section in the lib.rs docs.
Justification: I think the documentation on "what are the main types in this crate" / "how do I use this crate" ought to be front and center. Whereas the "background" on scope and goal is more secondary. The "Main Types" section is also quite a bit shorter than the "Scope and goals" section, so it means both fit "above the fold".
More concretely, I was reading the docs and trying to work out which type(s) could be considered the primary/default color representation(s). And it took me quite a bit of time to find it even though there was already a section explaining it.
=> Move docs on Main Types to the top

color/src/rgba8.rs
This test passes.
I've also made the existing test endian-aware.
=> Test that the bytemuck impl for `Rgba8` is sane

color/src/rgba8.rs
(And PremulRgba8.)
If the intention is for the bytes of R, G, B and A to always be in the same memory order, I believe this patch is required. The docstring on the method suggests that's the intention.
In the order of memory of `Rgba8::to_u8_array`, the red channel is at the lowest memory address and therefore (in little endian) the least significant byte. On a big endian system, using `from_le_bytes` would move the red byte to the highest memory address.
=> Always return little-endian packed value in Rgba8::to_u32

.github/workflows/ci.yml
This saves a lot of time and extra work.
=> ci: Run miri without cargo hack

CHANGELOG.md, color/src/parse.rs
The spec requires matching both lowercase and uppercase. The general solution is to copy the identifier into a temporary stack allocated buffer and do the case conversion there, before matching.
Fixes #105
=> Make color parsing case insensitive

CHANGELOG.md, color/Cargo.toml
When we use the `serde?/std` syntax for the feature, we end up with a public dependency on `serde` even when it isn't enabled or used. It isn't compiled, but it feels wrong. We don't need the `std` feature from `serde`, so no need to enable it and someone that does will already have it enabled.
=> Don't enable serde's `std` feature

CHANGELOG.md, color/src/rgba8.rs
Having the `From<Rgba8>` was unintentional and should have been `From<PremulRgba8>`.
A trait impl can't be deprecated with an attribute, so just note it in the doc comment.
=> Replace `From<Rgba8>` for `PremulColor` with `From<PremulRgba8>`

CHANGELOG.md, color/src/parse.rs
This makes it easier to parse them from a string with more concise code and not requiring a separate import of `parse_color`.
=> Add `FromStr` for `DynamicColor` and static colors

CHANGELOG.md, color/src/serialize.rs
As noted in § 14.4 of CSS Color 4 spec, colors specified in `xyz`, which is an alias of `xyz-d65`, are in the `xyz-d65` color space.
We already only have a predefined colorspace for `XyzD65` and not just `Xyz`, but were serializing it out in the shorter form.
=> Serialize `XyzD65` as `xyz-d65`

CHANGELOG.md, color/src/parse.rs
* § 4.2 of the CSS Color 4 spec states that the parsed alpha value will be clamped.
* Add a new enum `Mode` to help indicate whether we're in modern or legacy parsing mode. This can be used in additional ways in subsequent commits to improve the strictness of parsing.
* Reading an alpha value no longer automatically consumes trailing white space.
=> Clamp alpha during parse, other tweaks

color/src/colorspace.rs
=> Specify WHITE_COMPONENTS to machine precision

CHANGELOG.md, color/src/colorspace.rs
This fixes two 1-ULP rounding issues (first component in `XyzD50` and last component in `XyzD65`).
=> Specify XyzD50 and XyzD65 WHITE_COMPONENTS exactly

CHANGELOG.md, color/src/colorspace.rs
=> Add `impl ColorSpace` example

CHANGELOG.md, color/src/rgba8.rs
Closes #73.
The conversions from the packed u32 are easy to get wrong when implemented manually.
(On the other hand, these methods are also easy to use wrong.)
=> Implement `(Premul)Rgba8::from_u32` and `from_u8_array`

CHANGELOG.md, color/src/lib.rs, color/src/palette/css.rs
This is a common pattern in code in Vello examples and other places where they're just constructing an opaque color from the r,g,b values and a solid alpha.
=> Support construction from rgb8 values

color/src/cache_key.rs, color/src/colorspace.rs, color/src/lib.rs, color/src/serialize.rs
Instead of having `std` in scope and on by default, be `no_std` by default and use `std` more explicitly.
=> Be more `no_std`

color/src/parse.rs
This save an unnecessary bounds check, and fixes an impending Clippy lint Bruce notified me of:
```rust
warning: calling `as_bytes` after slicing a string
--> color/src/parse.rs:243:12
|
243 |         if self.s[self.ix..].as_bytes().first() == Some(&ch) {
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `&self.s.as_bytes()[self.ix..]`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#sliced_string_as_bytes
= note: `#[warn(clippy::sliced_string_as_bytes)]` on by default
```
=> Simplify str indexing

color/src/flags.rs
Reducing the doc's headline size.
=> Bump part of `Missing` docstring to second paragraph

CHANGELOG.md, color/src/flags.rs
The only alternative currently is `Missing::default()`, but that's not `const`.
=> Add `Missing::EMPTY` to allow getting a `const` empty `Missing`

color/src/colorspace.rs
This is useful to test the current implementation of absolute conversions (added in https://github.com/linebender/color/pull/139), but the main motivation is to have tests in place as preparation for manual implementations of `ColorSpace::{to_linear_srgb_absolute, from_linear_srgb_absolute}` for the non-D65 color spaces.
=> Test implicit vs explicit chromatic adaptation

color/src/colorspace.rs, color/src/dynamic.rs
Not sure if there is a reason why this doesn't already exists, but it's much nicer if you can do `BLACK.into()` instead of having to do `DynamicColor::from_alpha_color(BLACK)`.
=> Implement From<AlphaColor> for dynamic color

color/src/colorspace.rs
This builds on https://github.com/linebender/color/pull/139, which added absolute color conversions (conversions without chromatic adaptation). The default method implementations added there use the chromatically-adapting methods and undo adaptation through additional matrix multiplies. For efficiency, we can do the absolute conversions using matrices that do not include adaptation in the first place.
This PR does that for ProPhoto RGB. More to follow.
=> Add absolute conversion matrices for ProPhoto RGB

CHANGELOG.md, color/src/dynamic.rs
Previously all non-rectangular spaces were assumed to have saturation or chroma as second component, but this is not the case for `Hwb`.
[Color Module 4](https://www.w3.org/TR/css-color-4/#valdef-hwb-hwb) states:
> If the sum white+black is greater than or equal to 100%, it defines an
> achromatic color, i.e. a shade of gray; when converted to sRGB the R, G
> and B values are identical and have the value white / (white + black).
> ...
> Achromatic HWB colors no longer contain any hint of the chosen hue. In
> this case, the hue component is powerless.
=> Fix `powerless_to_missing` for `Hwb`

CHANGELOG.md, color/.clippy.toml, color/src/color.rs
Resolves #142. See also the discussion at https://github.com/linebender/vello/pull/830#discussion_r1982017666.
On x86, `f32::round` is slow as it calls out to the IEEE754-adhering libc function `roundf`. See, e.g., the branchy [glibc `roundf`](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/ieee754/flt-32/s_roundf.c;h=eb714e975e48f737c140a1dd666135759ac0ffe3;hb=HEAD) and [musl `roundf`](https://git.etalabs.net/cgit/musl/tree/src/math/roundf.c?h=c47ad25ea3b484e10326f933e927c0bc8cded3da) implementations. On AArch64, the compiler can make use of hardware instructions instead.
The knowledge that the output range is `0-255`, allows writing an almost-correct rounding implementation that doesn't require calling out to libc or branching. This is fast on both x86 and AArch64.
Codegen: …
=> Faster rounding in `{AlphaColor,OpaqueColor,PremulColor}::to_rgba8`

CHANGELOG.md, color/src/colorspace.rs
This PR fixes an error in CI when using nightly toolchain:
```
error[E0658]: use of unstable library feature `core_float_math`
```
This error can be seen in `vello` here:
- E.g. https://github.com/linebender/vello/actions/runs/15104337336/job/42450338042
Fix was entirely proposed by @DJMcNab here: [#vello > cargo doc CI failing with rust nightly @ 💬](https://xi.zulipchat.com/#narrow/channel/197075-vello/topic/cargo.20doc.20CI.20failing.20with.20rust.20nightly/near/519001092)
CI
=> Fix `core_float_math` nightly compilation.

CHANGELOG.md, Cargo.lock, Cargo.toml
Anyone depending on `color` can't currently build with nightly, so let's get this release out ASAP.
=> Prepare to release 0.3.1.

color/src/colorspace.rs
Miri now randomizes floating point precision of some operations that do not have guaranteed precision. That's causing CI to fail.
This works around the issue by using a looser bound when targeting Miri. That's a bit messy, but we'd probably like to notice when our normal targets suddenly fail to reach tight precision bounds.
=> Work around CI failing due to float precision randomization

color/src/dynamic.rs
This adds two tests interpolating from a fully transparent to a fully opaque color, in a rectangular space and in a cylindrical space.
This is motivated by https://github.com/linebender/color/pull/185, testing current behavior stays correct.
=> Test interpolation of transparent colors

CHANGELOG.md, color/src/color.rs, color/src/dynamic.rs, color/src/gradient.rs, color/src/lib.rs
Alternative implementiran of #185 that is NOT a breaking change. Functional wise it's the same (although there is no generalization of gradient iter code).
Fixes #184
=> Support interpolating in unpremultiplied (straight) alpha space

.github/workflows/ci.yml, color/src/colorspace.rs
CI is sometimes failing by flakey tests when run under Miri, and I cannot reproduce the failures locally under Miri. We'd probably like to release 0.3.2 anyway.
We test color operations to somewhat tight bounds, including those where we use floating point operations with unspecified precision. These sometimes cause tests to fail under Miri. While these failures might not be false positives technically, it seems Miri's approach to float error randomization has not fully stabilized yet (see, e.g., https://github.com/rust-lang/miri/pull/4558, which as of writing is a week-old change). We pass a flag to Miri to disable randomization for now in CI. The plan is to remove this flag once Miri's approach has become more stable.
Rather than doing another localized fix (as in …
=> (Temporarily) disable Miri's float randomization
